### ISSUE TITLE
Check for EC signature format needs to be added before trying to transcode it into DER

### ISSUE THREAD

**Issue by Muzosh** [web-eid/web-eid-authtoken-validation-php#5]
https://github.com/web-eid/web-eid-authtoken-validation-php/blob/ffcc2fa5491afe3b01fb0fcfb5938ca437e034bc/src/validator/AuthTokenSignatureValidator.php#L72-L77

This operation can make a valid signature become invalid!

My testing card returns ECDSA signature already in DER format (for example, my $signature before these lines is `MEYCIQD5VsViadEM3SrP9Fxn9zrVEqk3cEAqLqexM7IiIhGEjAIhANXRZe/vpPrCa8u44rrxnzchhhzVcWdXtHdkOx3ld4/0`, i.e. it is parsable into https://lapo.it/asn1js/).

The `openssl_verify` later on fails with error (returns -1), unless I comment the transcoding out (meaning, the validation library is not supposed to transcode that specific signature).

In my implementation, I used second condition `!ASN1::asn1map(ASN1::decodeBER($derSig)[0], DssSigValue::MAP)`. It basically says: try to decode this DER string into a sequence with two children of type integer (= DssSigValue:MAP). If it is successful, there is no need to do the transcoding and continue with the validation. `openssl_verify` returns 1.

**Comment by mrts** [comment]
Thanks! @groonguido, can you please review this?

**Comment by Muzosh** [comment]
Yes! I even noticed that phpseclib changed their logic and return values in some of the used functions, so my first example is no longer valid. I will update it and post it here.

**Comment by mrts** [comment]
Thanks a lot, very much appreciated!

**Comment by Muzosh** [comment]
@mrts
Why is value "origin" configurable in validation library (`->withSiteOrigin(new Uri("https://example.org"))`), when the origin value sent to the Web-eID App seems to be determined by Web-eID Web Extension based on where it did receive the authenticate request from `origin: (new URL(getSenderUrl(sender))).origin`?

I get that first origin value is for correct validation of the authentication token.
The second origin value is the one that gets transfomed authentication value to be signed by the card.

Wouldn't it be easier for system administrator that the first value is also created automatically? Is it even possible?
Was this designed by choice?

**Comment by mrts** [comment]
This was designed by choice and the origin needs to be configurable as there is no universal way to determine it in a HTTP server. For example, the server may be behind a load balancer or a reverse proxy, in this case the HTTP server is unaware of the origin hostname visible to the clients.

**Comment by Muzosh** [comment]
Ah, makes sense. Thank you.
